### PR TITLE
add pyarrow as required dependency for dagster duckdb

### PR DESCRIPTION
**Pull request by cmpadden**
Add `pyarrow` as required dependency as needed for `pd.read_parquet`.
  
  Before adding this dependency, when one attempts to materialize all assets, they are presented with the following error:

  ```
  ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
  A suitable version of pyarrow or fastparquet is required for parquet support.
  Trying to import the above resulted in these errors:
   - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
   - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
  ```

  This commit introduces the opinionated change of using `pyarrow` over the alternative of `fastparquet`.

### CODE REVIEW

**Comment by tacastillo** [comment]
What's the lib that needs `pyarrow`? Does it provide a suite of optional deps that we can install instead of just `pyarrow`?

ex. `pip install sqlalchemy[pyarrow]`?

**Comment by cmpadden** [comment]
> What's the lib that needs `pyarrow`? Does it provide a suite of optional deps that we can install instead of just `pyarrow`?
> 
> ex. `pip install sqlalchemy[pyarrow]`?

That's a good question - it's coming from Pandas `pd.read_parquet`. Their [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_parquet.html) states that they default to using the `pyarrow` engine.  However, it doesn't look like they include it as an _extra_ dependency.

```
 > pip install pandas[pyarrow]
Requirement already satisfied: pandas[pyarrow] in ./.direnv/python-3.11/lib/python3.11/site-packages (2.2.0)
WARNING: pandas 2.2.0 does not provide the extra 'pyarrow'
...
```

**Comment by tacastillo** [comment]
@cmpadden allegedly the extra for it is _two_ extras. https://pandas.pydata.org/docs/getting_started/install.html#other-data-sources

Wanna give it a shot and lmk if it's worth the effort? Otherwise I'll stamp approve!

**Comment by cmpadden** [comment]
> @cmpadden allegedly the extra for it is _two_ extras. https://pandas.pydata.org/docs/getting_started/install.html#other-data-sources
> 
> Wanna give it a shot and lmk if it's worth the effort? Otherwise I'll stamp approve!

Good find! I confirmed that `pandas[parquet]` did the trick as added in https://github.com/dagster-io/project-dagster-university/pull/7/commits/71d42f8c02720ea1b2d20ea8b30baa85895c4ffe.

**Review by tacastillo — APPROVED** [review]
alright, i'm lost on which PRs I've approved and not approved and which ones should wait until we officially finish the upgrade lol, but here's your stamp lol

**Pull request merged**
